services:
  bot-service:
    build: .
    shm_size: '256mb' # Give more room for image processing
    init: true        # Handles process cleanup
    restart: always
    env_file: .env.docker
    volumes:
      # Map the host data folder to the container
      - ./data:/app/data
      - ./src/logs:/app/src/logs